In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
x=np.array([1,2,4,3,5])
y=np.array([1,3,4,3,7])
print(x.shape)
print(y.shape)
print(x)
print(y)
x=x.reshape(-1,1)
print(x.shape)
print(x)
model=LinearRegression()
model.fit(x,y)
print(model.predict([[8]]))
y_pred=model.predict(x)
plt.scatter(x,y,color='r',marker='o')
plt.plot(x,y_pred,color='b',linewidth=2)
plt.xlabel('x')
plt.ylabel('y')
plt.show()
print(model.coef_)
print(model.intercept_)


(5,)
(5,)
[1 2 4 3 5]
[1 3 4 3 7]
(5, 1)
[[1]
 [2]
 [4]
 [3]
 [5]]
[10.1]


[1.3]
-0.30000000000000027


In [12]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDRegressor
import matplotlib.pyplot as plt

# Standardize features
scaler = StandardScaler()
x_stand = scaler.fit_transform(x.astype(float))

# Train SGDRegressor
sgdr = SGDRegressor(penalty='l2', alpha=0.15, max_iter=100)
sgdr.fit(x_stand, y)

# Predict for new input (scaled)
print(sgdr.predict(scaler.transform([[10]])))

# Predictions for training data
y_pred2 = sgdr.predict(x_stand)

# Plot results
plt.scatter(x_stand, y, color='g', marker='o')
plt.plot(x_stand, y_pred2, color='b', linewidth=2)
plt.xlabel('x_normalized')
plt.ylabel('y')
plt.show()

# Print coefficients
print(sgdr.coef_)
print(sgdr.intercept_)


[9.08333293]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1503: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


[1.28554359]
[2.72021682]
